<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_sampah_model extends CI_Model
{

    public $table = 'jenis_sampah';
    public $id = 'id_jenis_sampah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jenis_sampah', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_sampah', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('foto_sampah', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('remove', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jenis_sampah', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_sampah', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('foto_sampah', $q);
	$this->db->or_like('active', $q);
	$this->db->or_like('remove', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jenis_sampah_model.php */
/* Location: ./application/models/Jenis_sampah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-25 09:20:26 */
/* http://harviacode.com */